### ISSUE TITLE
Add c# project for enums on fuse core and common

### ISSUE THREAD

**Issue by texone** [TheFuseLab/VL.Fuse#10]

**Comment by everyoneishappy** [comment]
The project is there.  I'm not super familer with the type forwarding workflow, but seems to work ok.  Might just check with @vvvv-dottore as to best practice for referencing before setting up the same in the other Fuse Repos.

**Comment by everyoneishappy** [comment]
@texone  would be good to move any remaining patching enums still in the main sln file to this one
