### ISSUE TITLE
Pin renaming on low level nodes

### ISSUE THREAD

**Issue by everyoneishappy** [TheFuseLab/VL.Fuse#15]
I'd like to do a little renaming and consistency checking on the nodes in .Core & .Common.
This would be nice to do sooner rather then later so there are less patches and modules affected (broken).  

An example would be changing noise and SDF nodes from using 'x' to Input(probably the way to go), Position or Domain  (a lot of SDF nodes could have a position pin separate to their domain)

Another example would be a lot of the intrinsic function nodes could have more helpfully named parameters.  While they do currently actually follow the referenced functions I think we can do better to make it easy for ppl not familiar with HLSL. 

Take lerp node:
lerp(x, y, s)

could be 
lerp(Input, Input2, Mix)

another example:
Current: Bias(x, Control)
-> Bias(Input, Control) 

In both examples I'd propose to avoid x ,y etc as this is easily confused with components and swizzling.

For multiple inputs we currently have a mix of upper and lowercase (a, b), (x, y), (Input, Input2) & (Values, Values2)
I think the best would be to be consistent with VL style which is Input, Input2, InputN

The atomic nodes in Fuse.Core.Math seem to use values, values2, valuesN, this may or may not be worth changing to the VL convention...   

Kind of seems like a PITA but there are both human and programmatic advantages to consistency.

**Comment by texone** [comment]
Done for the math package

**Comment by everyoneishappy** [comment]
Working on this for main Fuse Repo now

**Comment by everyoneishappy** [comment]
Almost all done.  I've not done the SDF nodes yet, but they are gonna be overhauled imminently anyway.   It seems lib patches are fine but help patches do indeed get broken.
