### ISSUE TITLE
Finish Noise documentation

### ISSUE THREAD

**Issue by sebescudie** [TheFuseLab/VL.Fuse#50]
- [x] Check _What is Fractal Brownian Motion_
- [x] Update FBM help patch with Kyle's info
- [x] Domain displacement example
- [x] Landscape
- [x] Noise Reference ?

**Comment by everyoneishappy** [comment]
Couple of the new patches could still use some formatting / comments

**Comment by sebescudie** [comment]
Have not pushed yet but I'm on it :)
