### ISSUE TITLE
Raymarch (Material) does not seem to work with VolumeSDF

### ISSUE THREAD

**Issue by sebescudie** [TheFuseLab/VL.Fuse#51]
- Gamma version : 2021.4 526
- Fuse version : latest `develop`, ca8d150e26bddb1e4fc19323958e8be7617c5d39

Was trying to make a small HowTo for the VolumeSDF node, using the [Stanford Dragon asset from FieldTrip](https://github.com/everyoneishappy/FieldTrip/blob/master/Assets/Stanford%20Dragon.dds). When using the `Raymarch (Basic)` node, the dragon renders fine, but using `Raymarch (Material)`, it only shows a box.

<img src=https://user-images.githubusercontent.com/8690430/137621835-17fd0464-44d6-4283-ab11-56c63f3db39f.png width=300 />

<img src=https://user-images.githubusercontent.com/8690430/137621955-6d0d1999-ebc6-4846-b2d6-a06e2e830cdc.png width=300 />

After trying to use `Raymarch (Material)`, gamma stays in Hot Swapping state forever (static red bar under the quad menu) and ends up being unresponsive.

**Comment by azeno** [comment]
I fear this needs a PR in Stride itself. The culprit seems to be the blocking `WaitForResult` in this line:
https://github.com/stride3d/stride/blob/7e836297cb5930c01e6dfa0183e7f3cc64748fb6/sources/engine/Stride.Rendering/Rendering/DynamicEffectInstance.cs#L60

triggering https://github.com/stride3d/stride/blob/7e836297cb5930c01e6dfa0183e7f3cc64748fb6/sources/engine/Stride.Rendering/Rendering/EffectSystem.cs#L165 which schedules the continuation on the same thread - at least I don't see any code which would ensure that the continuation is scheduled on another thread.

**Comment by tebjan** [comment]
@sebescudie was this working in earlier versions?

**Comment by sebescudie** [comment]
@azeno Thanks for the pointer! Not much I can do on my side sadly :)

@tebjan Just tried with [402](https://teamcity.vvvv.org/viewLog.html?buildId=34737&buildTypeId=vvvv_gamma_Build&tab=artifacts&branch_vvvv_gamma=preview%2Fgamma-2021.4) and had the same behavior. Earlier versions I tested would either throw exceptions or give red nodes (because of newly introduced stuff in Gamma that were not there back then).

**Comment by azeno** [comment]
Just did a PR which fixes this issue. Please close once it's accepted and our Stride version updated.

**Comment by sebescudie** [comment]
Thanks @azeno, the freezing issue is fixed. 

I'm keeping this one open though, because the VolumeSDF still does not render with a `Raymarch (Material)`. 
Tested with 2021.4 preview 568 and latest Fuse from `develop` (8248761a0745fd9566766b63d32b650544824291).

**Comment by everyoneishappy** [comment]
I'm pretty sure it's the sampler not being setup correctly when used in material system.   Could this be related? https://github.com/vvvv/VL.StandardLibs/issues/130

**Comment by everyoneishappy** [comment]
This poor module had been quite the venn diagram of overlapping issues...  One step closer with vvvv/VL.StandardLibs#489 fixed.  But still some funky stuff with the sampler.   Demo patch in  9981cfcdf054cef6e93155e47442d70c5a6ad283

Will not work on open, then if you change some things on the sampler it does, but also seems to ignore the actual sampler settings.  @tebjan would you have any advice?
