### ISSUE TITLE
Materials seem to be compiled twice

### ISSUE THREAD

**Issue by tebjan** [TheFuseLab/VL.Fuse#54]
just noticed that materials with fuse shader generator nodes compile two times. Once there is an error and then a second time, it looks like something is a frame too late, which causes the behavior of first generating an invalid material.
You can also see that it is blinking red first, and then blinking green.

The shader should be generated in the callback `GenerateShaderSource`: [Stride.Rendering/Rendering/Materials/IComputeNode.cs#L25](https://github.com/stride3d/stride/blob/master/sources/engine/Stride.Rendering/Rendering/Materials/IComputeNode.cs#L25)

this is the compilation event of the sink, it also passes the generator context which tells you whether it is a material or custom shader.

**Comment by texone** [comment]
think this is working now with the new version
