### ISSUE TITLE
Buffers and textures don't work in materials.

### ISSUE THREAD

**Issue by tebjan** [TheFuseLab/VL.Fuse#55]
I think this can easily be fixed by putting resources like buffers or textures into `rgroup PerMaterial` and using the `stage` keyword:

```c
rgroup PerMaterial
{
    stage Texture2D InputTexture;
}
```

for reference: [VL.Stride.Runtime/src/Effects/ShaderFX/Texture/DeclTexture.sdsl](https://github.com/vvvv/VL.Stride/blob/preview/gamma-2021.4/packages/VL.Stride.Runtime/src/Effects/ShaderFX/Texture/DeclTexture.sdsl)

everyoneishappy:
Yes indeed that should work and does not. Actually anything texture sampling related seems to have trouble when fed into the material system via ToShaderFX. tebjan I think this is the same cause as the SDF volume not working correctly in the material system (and probably some other things like the VAT stuff)
is there some resource registration or manegment that needs to be taken care for on the VL side?
looking at the emitted sdsl in the log folder for this and also the shaderFX sample level, which does work
the actual sdsl lines to sample the texture seem the same in both, but I can see in the debug info on the ShderFX one it lists the resources for the texture and sampler as being bound.  It does not list these in the Fuse based one.  The variable declaration for texture and sampler looks the same though

**Comment by texone** [comment]
Looks like there is an another problem 

```
shader Shader_1125817681 : VS_PS_Base, ComputeFloat4
{
    rgroup PerMaterial{

        [Link("input_258")]
        stage Texture2D input_258;

        [Link("input_260")]
        stage SamplerState input_260;

    }





    override float4 Compute()
    {
        float4 result_263 = input_258.SampleLevel(input_260,streams.TexCoord, 0);
        float4 outputParam_1435 = result_263;

        return outputParam_1435;
    }
};

this shader is not working guess we need to investigate further with tebjan

**Comment by texone** [comment]
Added a testpatch 55#Buffers and textures in materialsl.vl in R&D/_Issues

**Comment by texone** [comment]
Basically have been two problems Texturing Mixin was missing and rgroup, added input handling to put resources into rgroup and values into cbuffer seems to work now

**Comment by everyoneishappy** [comment]
awesome, thanks for looking in to this!  Nice to name the demo files like that too- I think we should adopt this as standard operating procedure
