### ISSUE TITLE
Not all combinations of `GpuValue<T>` work when connecting any `T`

### ISSUE THREAD

**Issue by azeno** [TheFuseLab/VL.Fuse#56]
We need a good fallback option here https://github.com/TheFuseLab/VL.Fuse/blob/develop/src/Fuse/Monadic.cs#L30

Currently it throws an exception, some sort of warning would be better.

Example patch can be found at https://discourse.vvvv.org/t/some-nodes-hide-render-windows/19951/3 where  a `Spread<Vector2>` gets connected to a `GpuValue<Spread<Vector2>>`
![grafik](https://user-images.githubusercontent.com/573618/141092346-3954f980-ee34-47e2-a2d3-e68ed9960bb8.png)

**Comment by texone** [comment]
Any suggestions on how to achieve this?
