### ISSUE TITLE
Fuse crashing VVVV .net unhandled exception error CS0246

### ISSUE THREAD

**Issue by rofoto** [TheFuseLab/VL.Fuse#57]
How to replicate the crash. : Make new vvvv patch, add fuse dependency, start scrolling list of examples from dependency menu. Crash 

Crash Report. Screen shot of the window that cannot be copy/pasted and the text of the crash attached below. 

![InkedScreenshot_4_LI](https://user-images.githubusercontent.com/13305754/143336378-c85c08f8-6000-4aa1-9d59-eee948e74603.jpg)
[20211125_Crash_report.txt](https://github.com/TheFuseLab/VL.Fuse/files/7599493/20211125_Crash_report.txt)

**Comment by sebescudie** [comment]
Hey, may I ask which version of vvvv you're using? Thanks. 

**Edit** sorry, just saw the crash report! Fuse is meant to be used with gamma 2021.4, so upgrading to latest should fix your issue.

**Comment by rofoto** [comment]
Just updated and yes this crash is solved. Thanks
