### ISSUE TITLE
Resource Descriptors

### ISSUE THREAD

**Issue by natan-sinigaglia** [TheFuseLab/VL.Fuse#74]
dictionary is a bit too generic type
i thing we should have an interface
IResourceDescriptor
We could have nodes like this one, that are preconfigured for certain common resources:
![image](https://user-images.githubusercontent.com/6460926/215294759-badaab44-0525-4586-92ba-809d16d1254d.png)
![image](https://user-images.githubusercontent.com/6460926/215294767-73392b74-cc1d-4c70-a3eb-7e2a9e643c4a.png)

**Comment by texone** [comment]
Added four nodes to describe resource 
![image](https://user-images.githubusercontent.com/38135/230170506-b40ccd9b-32b7-4d60-a00a-e1db17dab9d2.png)
![image](https://user-images.githubusercontent.com/38135/230170555-73d0a377-3fd8-4076-81c9-0e1c776b55b2.png)
![image](https://user-images.githubusercontent.com/38135/230170633-3e7fd718-0e93-4596-8317-a0570f6a4e91.png)
![image](https://user-images.githubusercontent.com/38135/230170683-ded522aa-9c30-46f4-b4a6-37989a2065b4.png)
![image](https://user-images.githubusercontent.com/38135/230170731-1bc82645-a1f2-4bbb-9b8b-4896b3d21b35.png)
