### ISSUE TITLE
Invoke issue in particles

### ISSUE THREAD

**Issue by natan-sinigaglia** [TheFuseLab/VL.Fuse#77]
patch: HowTo Use Textures as VectorField

looks like there's an issue in the Texture2DVectorField node, specifically related to the invoke inside it.

![image](https://user-images.githubusercontent.com/6460926/218281146-0cb09988-e478-46e9-b5b4-741bb5236428.png)

**Comment by texone** [comment]
Adapted to new invoke seems to work now
