### ISSUE TITLE
Get vertex id when rendering meshes

### ISSUE THREAD

**Issue by texone** [TheFuseLab/VL.Fuse#79]
When possible provide id when using geometry nodes to be able to read from buffers

**Comment by tebjan** [comment]
you just have to inherit from `VertexIDStream` and call `AssignVertexID();` in the vertex stage:
https://github.com/vvvv/VL.Stride/blob/preview/2022.5/packages/VL.Stride.Runtime/src/Effects/Common/VertexIDStream.sdsl

**Comment by texone** [comment]
Added VerexID Generation to material extension and draw shader
