### ISSUE TITLE
Find solution for TransformSDF not working

### ISSUE THREAD

**Issue by texone** [TheFuseLab/VL.Fuse#89]
This is currently not compatible to the new delegate handling

**Comment by texone** [comment]
I have adjusted transform sdf to this
![image](https://user-images.githubusercontent.com/38135/230117154-9b39e468-fc8c-42fc-a017-a3f689084e3e.png)
looks like there are issues with the scaling
![image](https://user-images.githubusercontent.com/38135/230117358-3642c417-dbaf-4f8e-9920-14a6d4b996a0.png)
Can check this in Overview of sdf Operations?

**Comment by everyoneishappy** [comment]
fixed, thanks
