### ISSUE TITLE
Make sure world transformation gets passed correctly to the draw shader

### ISSUE THREAD

**Issue by tebjan** [TheFuseLab/VL.Fuse#91]
https://discourse.vvvv.org/t/how-to-transform-mesh-whild-using-drawshadergraph/21359

Have a look at the DrawShader implementation in VL.Stride to see how to [get the Word matrix from downstream](https://github.com/studiobruell/VL.StandardLibs/blob/main/VL.Stride.Runtime/src/Rendering/Effects/CustomDrawEffect.cs#L55).

**Comment by texone** [comment]
![image](https://user-images.githubusercontent.com/38135/229924333-d61393b7-9793-411f-b413-c82269684e70.png)
this should do the trick
